### PR TITLE
Full elementary odin 6.0 support

### PR DESCRIPTION
**Pull request by andirsun**
## Before
Screenshot from 2021-08-15 15 51 05
## After
Screenshot from 2021-08-15 16 52 56

Fix Switches initialization.
Improve space between switches. 
Remove some console validations.
Rounded corners with Libhandy

### CODE REVIEW

**Comment by andirsun** [comment]
Hey @PlugaruT Elementary os 6 ODIN is out! 
What do you think about drop Support for HERA ?

**Comment by PlugaruT** [comment]
> Hey @PlugaruT Elementary os 6 ODIN is out! 
> What do you think about drop Support for HERA ?

Yes, sounds good. Let's drop support for hera. Thanks

**Comment by prateekmedia** [comment]
@amidmajd Please also change the dependencies of workflow, due to that the build is failing.
https://github.com/PlugaruT/wingpanel-monitor/blob/17e81c63dd007723bde6d33bef454f01e324c5fe/.github/workflows/main.yml#L15

**Comment by prateekmedia** [comment]
@PlugaruT After merging this please also update the screenshot as net speed indicator icon have changed, and the screenshot is old.

**Comment by PlugaruT** [comment]
@andirsun can you please do that? 🙏  I don't run eOS now and can't run the app. Thanks

**Comment by andirsun** [comment]
@PlugaruT Done!, ready to merge.

**Comment by andirsun** [comment]
Hey @PlugaruT thanks for review and merge. 
I really like your project and I want to implement some new features. 
Do you know if its possible package this as a flatpak ?

**Comment by PlugaruT** [comment]
@andirsun if you want, I can add you as a collaborator to the project and take it from there.
I am no longer using eOS, can't test the new stuff.
What do you think?

**Comment by andirsun** [comment]
> @andirsun if you want, I can add you as a collaborator to the project and take it from there.
> I am no longer using eOS, can't test the new stuff.
> What do you think?

Sure !, thanks Dude.

**Comment by PlugaruT** [comment]
Invite sent ✈️

**Pull request merged**
